### ISSUE TITLE
Error while creating Shared Drive

### ISSUE THREAD

**Issue by mjain234** [ParveenBhadooOfficial/Create-Google-Shared-Drive#13]
I am facing this problem whenever i am creating a shared drive "Process Failed!SyntaxError: Unexpected token < in JSON at position 0", please help me regarding this...

**Comment by ParveenBhadooOfficial** [comment]
Are you able to create Shared Drives using drive.google.com ?

**Comment by mjain234** [comment]
How can I create that?
