### ISSUE TITLE
got following issue while trying to create drive

### ISSUE THREAD

**Issue by uzemalik** [ParveenBhadooOfficial/Create-Google-Shared-Drive#5]
Process Failed!TypeError: Cannot read property '0' of undefined

**Comment by ParveenBhadooOfficial** [comment]
Can you check if you can create Shared Drive using Google Drive App

**Comment by innowebka** [comment]
Got the same error and how to fix it ?
Process Failed!TypeError: Cannot read property '0' of undefined 
**or does this work with edu mail ?**

**Comment by innowebka** [comment]
> 
> 
> Read the repo readme carefully. 😅

so only works with gsuite business plus accounts right ?

**Comment by ParveenBhadooOfficial** [comment]
Precisely. Yes.

**Comment by innowebka** [comment]
> 
> 
> Precisely. Yes.

**edu mail ?**

**Comment by ParveenBhadooOfficial** [comment]
Yes. Only those supports. Basically every edu is business level GSuite account.

**Comment by innowebka** [comment]
**Whats the right way to add keys**
client_id: '000000000000000000.apps.googleusercontent.com'
**or** 
client_id: 000000000000000000.apps.googleusercontent.com
**without the apostrophe or with the apostrophe ?**
